### ISSUE TITLE
Where do the node-locust and locust executables live?

### ISSUE THREAD

**Issue by joshuafernandes** [jspdown/node-locust#3]
Hi

So attempting to try and use this but can't seem to locate where the `node-locust` and `locust` executables are found as per the usage instructions. 

The npm install didn't render any binaries, and attempting to use the index.js file here as the binary throws :+1: 
```
./node_modules/locust-node/index.js: line 1: syntax error near unexpected token `('
./node_modules/locust-node/index.js: line 1: `const path = require('path');'
```

Are there some steps missing in the readme?

Cheers

**Comment by jspdown** [comment]
Hello @joshuafernandes `locust` is the official locust script http://docs.locust.io/en/stable/installation.html#install-for-development. 
The README isn't clear about the `node-locust` binary. It's just the index.js script. 

Locust have changed quite a lot since I wrote this package (prior to locust 1.0) Some changes would be required in the dummy.py on the communication with locust. I couldn't make it work with their latest releases. 

I sadly don't have time to allocate to this project but I would be happy to accept external contributions.
